FROM ubuntu

RUN apt update -y
#RUN apt install -y wget dpkg curl git python3 python3-pip
RUN apt-get update -y
RUN apt install git -y
#RUN usermod -s /usr/sbin/nologin root
#RUN adduser sidecar
RUN mkdir /results
VOLUME /results
COPY ./upload_script.sh ./
#COPY /report_xml.xml /
#RUN chown -R sidecar /results
#RUN chown -R sidecar /upload_script.sh
#USER sidecar
RUN chmod +x /upload_script.sh
ENTRYPOINT [ "/upload_script.sh" ]








