apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: zap-scan-taskrun
spec:
  taskSpec:
    steps:
    - name: zap-scan-step
      image: owasp/zap2docker-stable
      volumeMounts:
        - name: my-volume
          mountPath: /zap/wrk
      command: ["zap-baseline.py"]
      args:
      - "-I"
      - "-t"
      - "http://20.81.109.78:3000/"
      - "-g"
      - "gen.conf"
      - "-x"
      - "report_xml.xml"
    - name: github-push-step
      image: rounak007/github-push-image-repo
      volumeMounts:
        - name: my-volume
          mountPath: /results
    volumes:
      - name: my-volume
        emptyDir: {}

 



